# Generated by Django 3.2 on 2021-05-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winemakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winemakers',
            old_name='description',
            new_name='location',
        ),
    ]
