# Generated by Django 3.2 on 2021-05-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winemakers', '0002_rename_description_winemakers_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winemakers',
            old_name='title',
            new_name='producer_name',
        ),
    ]
